"""Initial migration

Revision ID: ac537979aa61
Revises: 
Create Date: 2024-08-06 16:06:38.676292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac537979aa61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_manager_id', table_name='file_manager')
    op.drop_index('ix_file_manager_uid', table_name='file_manager')
    op.drop_table('file_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_manager',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_format', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_extension', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='file_manager_pkey')
    )
    op.create_index('ix_file_manager_uid', 'file_manager', ['uid'], unique=True)
    op.create_index('ix_file_manager_id', 'file_manager', ['id'], unique=False)
    # ### end Alembic commands ###
